### ISSUE TITLE
Sourcemap is likely to be incorrect

### ISSUE THREAD

**Issue by autumnalriver** [onebay/vite-plugin-imp#7]
When run build script, the command line displays as follows:

Sourcemap is likely to be incorrect: a plugin (vite-plugin-imp) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

**Comment by psaren** [comment]
> When run build script, the command line displays as follows:
> 
> Sourcemap is likely to be incorrect: a plugin (vite-plugin-imp) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help

Could you provide a minimal reproduce repo or the steps to reproduce the behavior.

**Comment by autumnalriver** [comment]
The steps to reproduce:

1. Download the repo https://github.com/cawa-93/vite-electron-builder;
2. Extract the downloaded zip file and cd into the directory `vite-electron-builder-main`;
3. Install the dependencies: `npm install` or `yarn`;
4. Add the UI component lib: `npm install element-plus --save` or `yarn add element-plus`
5. Add the plugin : `npm install vite-plugin-imp -D` or `yarn add vite-plugin-imp -D`;
6. Edit the `vite.config.js` follow the instructions;
7. In the file `packages/render/src/components/home.vue`, import and use the component `ElButton`;
8. Run the compile script: `npm run compile` or `yarn compile`, then the tips appears;

```shell
packages/renderer/
  vite v2.1.2 building for production...
  ✓ 30 modules transformed.
rendering chunks (1)...  Sourcemap is likely to be incorrect: a plugin (vite-plugin-imp) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
```

**Comment by psaren** [comment]
Fixed in v2.0.5!

**Comment by autumnalriver** [comment]
Great! It works normally after update.

**Comment by autumnalriver** [comment]
Great! It works normally after update.

**Comment by mushan0x0** [comment]
@psaren V2.0.7 still encountered this problem when processing the antd library.

**Comment by psaren** [comment]
@mushan0x0 
Providing a reproducible repo can help me locate the problem.

**Comment by Winston-Guess** [comment]
I still have this issue in 2.8.6. Anyone found a cure?

**Comment by GuichiZhao** [comment]
Reopen this please, the issue appears agian

**Comment by Emily-0616** [comment]
i have the same problem！！！

**Comment by ThatBrianDude** [comment]
Im getting the inccorect line number in chrome. 
I have this issue but its locked.

https://github.com/onebay/vite-plugin-imp/issues/7#issuecomment-877030438

Please unlock or provide a solution...
